### ISSUE TITLE
Idea: auto-approve CODE_CHANGEs via git integration

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/kio-cli#3]
Just an idea: we could allow approving application versions (CODE_CHANGE) automatically by looking for appropriate patterns (e.g. approved/merged pull requests) in git history.
- The "approver" keeps the Kio CLI running on his computer (with personal OAuth token)
- "Somebody" creates a pull request (PR)
- The "approver" approves (:+1: comment) and merges the PR
- A new application version is created (by CD pipeline when deployment is triggered)
- The running Kio CLI automatically detects the new application version, finds the approved PR and therefore approves the application version

**Comment by sarnowski** [comment]
but we don't want a new version for each PR right? Only if we trigger a deployment.

**Comment by hjacobs** [comment]
Yes, this is point 4 "new application version is created" (by CD pipeline)

**Comment by hjacobs** [comment]
I personally think this auto-approve feature is far better than requiring people to approve versions "unseen".

**Comment by sarnowski** [comment]
so if the kio cli finds a new version, it should look if the code in it was approved by me with the pull request - but how do I define "code in it" again?

**Comment by hjacobs** [comment]
@sarnowski I don't know exactly, but some heuristic is still better than "just" approving a version I don't even have looked at (the code) at all

**Comment by hjacobs** [comment]
@sarnowski it could e.g. check strictly linear cases: diff to latest approved [by me] version and make sure that all commits/PR to current version are approved by me too

It does not need to cover 100% of all cases as we can still approve manually if needed.

**Comment by hjacobs** [comment]
or it could optionally be less strict and just check that the most recent commits are approved by me, i.e. assuming that I looked at the code and therefore also approve the history before

**Comment by hjacobs** [comment]
The less strict version would work for me: I trust my colleagues :smirk: and this makes sure I had a look at the most recent code changes.

**Comment by prayerslayer** [comment]
Nice idea :+1:

**Comment by harti2006** [comment]
Approvals are not handled in Kio anymore, so this feature got obsolete. Sorry for the work that already went into it :-/
